# Generated by Django 4.2.1 on 2023-05-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('comment', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Оборудования',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Спецификация',
            },
        ),
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255, verbose_name='Названия файла')),
                ('fileImage', models.FileField(upload_to='equipment_files/', verbose_name='Файл')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateModify', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.equipment', verbose_name='Оборудования')),
                ('specificationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.specification', verbose_name='Спецификация')),
                ('userDownloadId', models.ManyToManyField(blank=True, related_name='user_download_id', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи скачали')),
                ('userModifyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменил')),
                ('userUploadId', models.ManyToManyField(blank=True, related_name='user_upload_id', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь загрузил')),
            ],
            options={
                'verbose_name_plural': 'Список Оборудование',
            },
        ),
    ]
