# Generated by Django 4.2.1 on 2023-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
