# Generated by Django 4.2.1 on 2023-05-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_specification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlist',
            name='userUploadId',
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='userUploadId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload_id', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь загрузил'),
            preserve_default=False,
        ),
    ]
