# Generated by Django 4.2.1 on 2023-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_equipmentlist_useruploadid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='fileImage',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
